name: Python linting

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Python dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          $HOME/.poetry/bin/poetry install
      - name: Check formatting with black
        run: |
          $HOME/.poetry/bin/poetry run black --check ./
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Python dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          $HOME/.poetry/bin/poetry install
      - name: Run pylint
        run: |
          $HOME/.poetry/bin/poetry run pylint *.py
